config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'talks/test' => 'talks#test'
  root 'talks#top'
  
  resources :folders do
    collection do
      get 'search'
    end
    resources :talks
    collection do
      get 'talks/search' => 'talks#search'
    end
  end
  resources :flashcards
  
  # get 'folders/search' => 'folders#search'
  # get 'talks/search' => 'talks#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  validates_presence_of :word,:answer 
end

app/models/folder.rb
class Folder < ApplicationRecord
    has_many :talks , dependent: :destroy
    validates :name , presence: true
    validates :name,    length: { maximum: 25 }      # 「25文字以下」
end

app/models/talk.rb
class Talk < ApplicationRecord
  validates :text , presence: true
  belongs_to :folder ,optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource)
    '/users/sign_in' # サインアウト後のリダイレクト先URL
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :set_flashcard , only: [:edit , :update ,:destroy]

  def index
    @flashcards = Flashcard.order("RAND()")
  end

  def new
    @flashcard = Flashcard.new
  end

  def create
    @flashcard = Flashcard.new(flash_params)
    if @flashcard.save
      redirect_to "/flashcards"
    else
      redirect_to "/flashcards/new"
      flash[:alert] = "保存できませんでした"
    end
  end

  def edit
  end

  def update
    @flashcard.update(flash_params)
    redirect_to "/flashcards"
  end

  def destroy
    @flashcard.destroy
    redirect_to "/flashcards"
  end

  private
  def flash_params
    params.require(:flashcard).permit(:word, :answer)
  end

  def set_flashcard
    @flashcard = Flashcard.find(params[:id])
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:edit,:update,:destroy]
  before_action :authenticate_user!

  def index
    @folder = Folder.all.order('id DESC')
    # binding.pry
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new(folder_params)
    if @folder.save
      redirect_to "/folders"
    else
      redirect_to "/folders/new"
      flash[:alert] = "保存できませんでした"
    end
  end

  def edit
  end

  def update
    @folder.update(folder_params)
    redirect_to "/folders"
  end

  def destroy
    @folder.destroy
    redirect_to "/folders"
    # binding.pry
  end

  def search
    @folders = Folder.where("name LIKE(?)", "%#{params[:keyword]}%") unless params[:keyword] == ""
    @word = params[:keyword]
  end



 private
  def folder_params
    params.require(:folder).permit(:name)
  end

  def set_folder
    @folder = Folder.find(params[:id])
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:edit,:update,:destroy]

  def top
  end

  def index
    @talks = Talk.where(folder_id: params[:folder_id]).order("created_at DESC")
    @folders = Folder.all.order('id DESC')
    #form_forで使う変数↓
    @talk = Talk.new 
    @folder = Folder.find(params[:folder_id])
  end

  def create
    @talk = Talk.new(talk_params)
    if @talk.save
     redirect_to "/folders/#{params[:folder_id]}/talks"
    else
      redirect_to "/folders/#{params[:folder_id]}/talks"
      flash[:alert] = "テキストが空です"
    end
  end

  def edit
    @folder = Folder.find(params[:folder_id])
  end

  def update
    @talk.update(talk_params)
    redirect_to "/folders/#{params[:folder_id]}/talks"
  end

  def  destroy
    @talk.destroy
    redirect_to folder_talks_path(params[:folder_id])
  end

  def search
    @folders = Folder.all
    @talks = Talk.where("text LIKE(?)", "%#{params[:keyword]}%") unless params[:keyword] == ""
    @word = params[:keyword]
  end


  private
  def talk_params
    params.require(:talk).permit(:text).merge(folder_id: params[:folder_id])
  end

  def set_talk
    @talk = Talk.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/flashcards/edit.html.haml
.flash-create
  = form_with model: @flashcard, local: true, class: 'flash-form' do |f|
    = f.label :"Edit Flashcard" , class:"flash-word"
    = f.text_field :word, class:"word-form" ,placeholder:"Word"
    = f.text_area :answer, class:"answer-form" ,placeholder:"Answer"
    = f.submit "OKAY" , class:"flash-submit-btn"

app/views/flashcards/index.html.haml
.talk-header
  .header-logo
    = link_to 'TALK to MYSELF ' , '/folders', class:"logo"
    = image_tag "https://img.icons8.com/wired/64/000000/edit.png" , class:"pen"

    = link_to  "/flashcards/new" do
      = image_tag "https://img.icons8.com/ios/50/000000/flashcards.png" , class: "new-word"

.flash-main
  - @flashcards.each do |flashcard|
    .flash-field
      .flash-space
        .word
          = flashcard.word
          
          = link_to 'Delete', flashcard_path(flashcard.id), method: :delete , class:"delete-btn" ,data: { confirm: '削除しますか？' }
          = link_to "Edit" , edit_flashcard_path(flashcard.id) ,method: :GET , class: "edit-btn"
          .answer-mark
            ▼
          .answer
            = flashcard.answer

-# .flash-main
-#   .flash-field
-#     .flash-space
-#       .word
-#         aaa
-#         .answer-mark
-#           ▼
-#         .answer
-#           aaaaaaaaaaaaaaaaaaaaaaa
-#           aaaaaaaaaaaaaaaaaa
-#           aaaaaa

-#   .flash-field
-#     .flash-space
-#       .word
-#         aaa
-#         .answer-mark
-#           ▼
-#         .answer
-#           bbbbbbb

app/views/flashcards/new.html.haml
.notifications
  - if flash[:alert]
    %p= flash[:alert]

.talk-header
  .header-logo
    = link_to 'TALK to MYSELF ' , '/folders',class:"logo"
    = image_tag "https://img.icons8.com/wired/64/000000/edit.png" , class:"pen"

.flash-create
  = form_with model: @flashcard, url: flashcards_path, local: true, class: 'flash-form' do |f|
    = f.label :"Create New Flashcard" , class:"flash-word"
    = f.text_field :word, class:"word-form" ,placeholder:"Word"
    = f.text_area :answer, class:"answer-form" ,placeholder:"Answer"
    = f.submit "OKAY" , class:"flash-submit-btn"

app/views/folders/edit.html.haml
.edit-main
  .form
    = form_with model: @folder , local: true ,class: 'form' do |f|
      = f.label :"Edit Folder Name" , class:"word"
      = f.text_field :name, class:"talk-form" ,placeholder:"Edit Name"
      = f.submit "Edit" , class:"submit-btn"

app/views/folders/index.html.haml
.talk-header

  .header-logo
    = link_to 'TALK to MYSELF ' , '/folders', class:"logo"
    = image_tag "https://img.icons8.com/wired/64/000000/edit.png" , class:"pen"

  = link_to 'Sign_out', "/users/sign_out", method: :delete ,class: "sign_out"


  = link_to new_folder_path do
    = image_tag "https://img.icons8.com/carbon-copy/100/000000/create-new.png" , class:"new-folder"


  = link_to "/flashcards" do
    = image_tag "https://img.icons8.com/wired/64/000000/dictionary.png" , class:"new-folder"

  .header-search
    = form_tag('/folders/search',method: :GET) do
      %input{placeholder:"検索したいフォルダー", type:"search", name:"keyword", class:"input-search"}
      = button_tag type: "submit", class: "header-search-btn" do
        = image_tag("https://img.icons8.com/ios/50/000000/search.png")

.group-main
  .select-group
    .each-group
      - @folder.each do |folder|
        = link_to "#{folder.name}" , "/folders/#{folder.id}/talks" ,class:"fol"
        .btn
          = link_to "Edit" , edit_folder_path(folder.id) ,method: :GET , class: "edit-btn"
          = link_to 'Delete', "/folders/#{folder.id}", method: :delete , class:"delete-btn" ,data: { confirm: '削除しますか？' }

app/views/folders/new.html.haml
.notifications
  - if flash[:alert]
    %p= flash[:alert]


.talk-header
  .header-logo
    = link_to 'TALK to MYSELF ' , '/folders',class:"logo"
    = image_tag "https://img.icons8.com/wired/64/000000/edit.png" , class:"pen"

.form
  = form_with model: @folder,  local: true, class: 'folder-form' do |f|
    = f.label :"Create New folder;" , class:"folder-word"
    = f.text_field :name, class:"name-form" ,placeholder:"Name of Folder"
    = f.submit "OKAY" , class:"folder-submit-btn"

app/views/folders/search.html.haml
.talk-header

  .header-logo
    = link_to 'TALK to MYSELF ' , '/folders', class:"logo"
    = image_tag "https://img.icons8.com/wired/64/000000/edit.png" , class:"pen"

  = link_to 'Sign_out', "/users/sign_out", method: :delete ,class: "sign_out"


  = link_to new_folder_path do
    = image_tag "https://img.icons8.com/carbon-copy/100/000000/create-new.png" , class:"new-folder"


  = link_to "/flashcards" do
    = image_tag "https://img.icons8.com/wired/64/000000/dictionary.png" , class:"new-folder"

  %form.header-search
    = form_tag('/folders/search',method: :GET) do
      %input{placeholder:"検索したいメモ", type:"search", name:"keyword", class:"input-search"}
      
      = button_tag type: "submit", class: "header-search-btn" do
        = image_tag("https://img.icons8.com/ios/50/000000/search.png")

.group-main
  .select-group
    .each-group
      -if(@folders.blank? || @folders.length == 0)
        .no-result
          = "該当するフォルダーがありません"
      -else
        .hit-result
          ="検索結果 1-#{@folders.length}件"
        - @folders.each do |folder|
          = link_to "#{folder.name}" , "/folders/#{folder.id}/talks" ,class:"fol"
          .btn
            = link_to "Edit" , edit_folder_path(folder.id) ,method: :GET , class: "edit-btn"
            = link_to 'Delete', "/folders/#{folder.id}", method: :delete , class:"delete-btn" ,data: { confirm: '削除しますか？' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TalkToMyself
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/

    / %script{:src => "./top.js"}

    %link{href: "https://fonts.googleapis.com/css?family=Caveat" , rel: "stylesheet"}/
    %link{href: "https://fonts.googleapis.com/css?family=Londrina+Shadow" , rel: "stylesheet"}/
    %link{href: "https://fonts.googleapis.com/css?family=Amatic+SC:700", rel: "stylesheet"}/



  %body
    = yield

app/views/talks/edit.html.haml
.edit-main
  .form
    -# = form_with  local: true, class: 'form' do |f|
    = form_for [@folder,@talk], class: 'form' do |f|
      = f.label :"Edit Talk" , class:"word"
      = f.text_area :text, class:"talk-form" ,placeholder:"Let's talk to myself"
      = f.submit "Edit" , class:"submit-btn"

app/views/talks/index.html.haml
.notifications
  - if flash[:alert]
    %p= flash[:alert]


.talk-header
  %ul#menu
    %li.menu
      = image_tag "https://img.icons8.com/windows/32/000000/menu.png", style: "-webkit-user-select: none;" , class: "folder-list"
      %ul.child
        - @folders.each do |folder|
          %li.children
            = link_to  "#{folder.name}" , "/folders/#{folder.id}/talks" ,class:"each_folder"

  .header-logo
    = link_to 'TALK to MYSELF ' , '/folders' ,class:"logo"
    = image_tag "https://img.icons8.com/wired/64/000000/edit.png" , class:"pen"


  = link_to new_folder_path do
    = image_tag "https://img.icons8.com/carbon-copy/100/000000/create-new.png" , class:"new-folder"

  .header-search
    = form_tag('/folders/talks/search',method: :GET) do
      %input{placeholder:"検索したいメモ", type:"search", name:"keyword", class:"input-search"}
      = button_tag type: "submit", class: "header-search-btn" do
        = image_tag("https://img.icons8.com/ios/50/000000/search.png")


.talk-main
  .memos
    - @talks.each do |talk|
      .memo
        -# = simple_format(talk.text)
        = raw(talk.text.gsub(/\n/, "<br>"))
        -# = sanitize(simple_format(talk.text), :tags => %w(p br))
        = link_to 'Edit' , edit_folder_talk_path(params[:folder_id], talk.id) ,class: "edit-btn"
        = link_to 'Delete', folder_talk_path(params[:folder_id], talk.id), method: :delete , class:"delete-btn" ,data: { confirm: '削除しますか？' }

  .form
    -# = form_with  local: true, class: 'form' do |f|
    = form_for [@folder,@talk], class: 'form' do |f|
      = f.label :"Talk to Myself ;" , class:"word"
      = f.text_area :text, class:"talk-form" ,placeholder:"Let's talk to myself"
      = f.submit "TALK" , class:"submit-btn"

app/views/talks/search.html.haml
.talk-header
  %ul#menu
    %li.menu
      = image_tag "https://img.icons8.com/windows/32/000000/menu.png", style: "-webkit-user-select: none;" , class: "folder-list"
      %ul.child
        - @folders.each do |folder|
          %li.children
            = link_to  "#{folder.name}" , "/folders/#{folder.id}/talks" ,class:"each_folder"

  .header-logo
    = link_to 'TALK to MYSELF ' , '/folders' ,class:"logo"
    = image_tag "https://img.icons8.com/wired/64/000000/edit.png" , class:"pen"


  = link_to new_folder_path do
    = image_tag "https://img.icons8.com/carbon-copy/100/000000/create-new.png" , class:"new-folder"

  %form.header-search
    = form_tag('/folders/talks/search',method: :GET) do
      %input{placeholder:"検索したいメモ", type:"search", name:"keyword", class:"input-search"}
      = button_tag type: "submit", class: "header-search-btn" do
        = image_tag("https://img.icons8.com/ios/50/000000/search.png")


.talk-main
  -if(@talks.blank? || @talks.length == 0)
    .no-result
      = "該当するフォルダーがありません"
  -else
    .hit-result
      ="検索結果 1-#{@talks.length}件"
    .memos
      - @talks.each do |talk|
        .memo
          = raw(talk.text.gsub(/\n/, "<br>"))
          = link_to 'Edit' , edit_folder_talk_path(talk.folder_id, talk) ,class: "edit-btn"
          = link_to 'Delete', folder_talk_path(talk.folder_id, talk), method: :delete , class:"delete-btn" ,data: { confirm: '削除しますか？' }

app/views/talks/test.html.haml
-# .mainImage
-#   = image_tag "https://i.ytimg.com/vi/-OSSDuMkk70/hqdefault.jpg"
-# .thumbnails
-#   = image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiGNb36KY_-TMOPTuwglI2mtYi-YGH1T7b1URiYPRCUpMrN_AO" , width:20
-#   = image_tag "https://i.ytimg.com/vi/OzJiHFxT8aI/maxresdefault.jpg" , width:20
-#   = image_tag "http://animalsbirds.com/wp-content/uploads/2016/07/Funny-Animals-Dog-Photos.jpg" ,width:20

app/views/talks/top.html.haml
.container
  Hello, Bro
  .loader-container
    %div
    %div
    %div
    %div
    %div
  = link_to 'Talk to Myself ' , 'folders' , class: "tag"
  .spinner-container
    .spinner-path
      %div
      %div
      %div
      %div
%svg{:version => "1.1", :xmlns => "http://www.w3.org/2000/svg"}
  %defs
    %filter#gooey
      %fegaussianblur{:in => "SourceGraphic", :result => "blur", :stddeviation => "10"}
      %fecolormatrix{:in => "blur", :mode => "matrix", :result => "goo", :values => "1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 21 -7"}
      %feblend{:in => "SourceGraphic", :in2 => "goo"}